-- Generated by nwg-displays on 2026-09-25 at 22:47:45. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60.0",
    position = "1920x0",
    scale = 2.0,
    vrr = 0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0,
    vrr = 0
})
